#!/usr/bin/env node
/**
 * fetch-tracks.mjs
 *
 * Look up tracks against Apple's iTunes Search API and emit ready-to-paste
 * entries for `lib/music-data.ts`.
 *
 * Usage:
 *   node scripts/fetch-tracks.mjs scripts/songs.txt
 *
 * Input file format (one song per line, blank lines and `# ...` comments allowed):
 *   Blinding Lights — The Weeknd
 *   Day 'N' Nite — Kid Cudi
 *   Houdini — Dua Lipa
 *
 * The dash separator can be ` - ` or ` — ` (space-dash-space, em or hyphen).
 *
 * The script writes to stdout. To paste straight into your manifest, run:
 *   node scripts/fetch-tracks.mjs scripts/songs.txt > /tmp/tracks.txt
 * then copy `/tmp/tracks.txt` into the TRACKS array in `lib/music-data.ts`.
 *
 * No dependencies. Uses the global `fetch` available since Node 18.
 */

import fs from "node:fs";
import path from "node:path";

const inputPath = process.argv[2];
if (!inputPath) {
  console.error("usage: node scripts/fetch-tracks.mjs <songs.txt>");
  process.exit(1);
}

const lines = fs
  .readFileSync(path.resolve(inputPath), "utf8")
  .split("\n")
  .map((l) => l.trim())
  .filter((l) => l.length > 0 && !l.startsWith("#"));

if (lines.length === 0) {
  console.error("(no songs in input file)");
  process.exit(0);
}

/** Convert " — " / " – " / " - " to a normalized splitter. */
function splitTitleArtist(line) {
  // Try em dash, en dash, regular hyphen — in that order, with surrounding spaces.
  for (const sep of [" — ", " – ", " - "]) {
    const i = line.indexOf(sep);
    if (i !== -1) {
      return [line.slice(0, i).trim(), line.slice(i + sep.length).trim()];
    }
  }
  // No separator — treat the whole line as a search query (no artist filter).
  return [line, ""];
}

/** Slugify for stable track ids. */
function slug(s) {
  return s
    .toLowerCase()
    .replace(/['"`]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

/** Format a JS string literal (escapes backslash, quotes). */
function jsStr(s) {
  if (s == null) return '""';
  return JSON.stringify(String(s));
}

/** Hit iTunes Search and return the first matching song entry. */
async function lookup(title, artist) {
  const term = artist ? `${title} ${artist}` : title;
  const url =
    "https://itunes.apple.com/search?" +
    new URLSearchParams({
      term,
      entity: "song",
      limit: "5",
    }).toString();

  const res = await fetch(url, {
    headers: { "User-Agent": "personal-site-music-fetcher/1.0" },
  });
  if (!res.ok) throw new Error(`iTunes ${res.status} for "${term}"`);
  const data = await res.json();
  if (!data.results || data.results.length === 0) return null;

  // Prefer a result whose artistName matches what we asked for. iTunes
  // sometimes returns covers / wrong artists otherwise.
  if (artist) {
    const lc = artist.toLowerCase();
    const exact = data.results.find((r) =>
      r.artistName?.toLowerCase().includes(lc)
    );
    if (exact) return exact;
  }
  return data.results[0];
}

/** Bump artwork URL from 100x100 to 600x600 — the API returns small by default. */
function upscaleArt(url) {
  if (!url) return null;
  return url.replace(/\/\d+x\d+bb\.jpg$/, "/600x600bb.jpg");
}

/** Emit one TRACKS-style entry as TS source. */
function emitEntry(input, hit) {
  const id = slug(`${hit.trackName}-${hit.artistName}`);
  const lines = [
    "  {",
    `    id: ${jsStr(id)},`,
    `    title: ${jsStr(hit.trackName)},`,
    `    artist: ${jsStr(hit.artistName)},`,
  ];
  if (hit.collectionName) lines.push(`    album: ${jsStr(hit.collectionName)},`);
  if (hit.trackTimeMillis) {
    lines.push(`    duration: ${Math.round(hit.trackTimeMillis / 1000)},`);
  }
  const art = upscaleArt(hit.artworkUrl100);
  if (art) lines.push(`    albumArt: ${jsStr(art)},`);
  if (hit.previewUrl) lines.push(`    previewUrl: ${jsStr(hit.previewUrl)},`);
  lines.push("  },");
  return lines.join("\n");
}

const out = [];
for (const line of lines) {
  const [title, artist] = splitTitleArtist(line);
  process.stderr.write(`→ ${title}${artist ? `  ·  ${artist}` : ""} ... `);
  try {
    const hit = await lookup(title, artist);
    if (!hit) {
      process.stderr.write("not found\n");
      out.push(`  // not found: ${line}`);
      continue;
    }
    process.stderr.write(`ok  (${hit.trackName} — ${hit.artistName})\n`);
    out.push(emitEntry(line, hit));
  } catch (e) {
    process.stderr.write(`error: ${e.message}\n`);
    out.push(`  // error fetching: ${line} — ${e.message}`);
  }
}

console.log("// generated by scripts/fetch-tracks.mjs");
console.log(out.join("\n"));
